# Generated by Django 4.0 on 2021-12-07 12:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_field',
            field=jsonfield.fields.JSONField(default=['p2', 'test']),
        ),
    ]
