# Generated by Django 4.0 on 2021-12-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_cart_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_field',
        ),
    ]
