# Generated by Django 4.0 on 2021-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cart_cart_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_field',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
